# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812807f444fcad6ce4e34604776815536469230f927eb565106ef33e7eba4e7e42f22464c140c88782dcf8dff5b690eb7636a04df20ba22a21af3ed0bb0b8311

test:
  secret_key_base: dd37c7f49b00e6a29dfb1f108c49391bb7e1a1b2f86ecdba4dc1e98818a28a590804a9ac0b067e48b17a751b90ccfcd520ca0a94618e0ea51b4a65d20bfc4408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
